
#  printing hellow world!
print("Hello world")

# #  takeing user input!
ui = input("Enter a string: ")
print(ui)

# # takeing integer input from user
a = int(input("Enter a number: "))
print("You have enterad : ", a)


# # adding two numbers
a = 5
b = 6
print(a+b)


# # concatening two string
first_name = input("Enter first name: ")
last_name = input("Enter last name: ")
print("My name is ", first_name, " ", last_name)

# for loop
for a in range(10):
    print(a)


##lists in python
fruits = ["apple", "Banana", "Orange ", "mango"]
print(fruits)
print(fruits[2])
print(fruits[-1])


